name: site
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.11.x

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
