export default function jumpDetailPoster(params: Record<string, any>) {
  return [
    {
      type: 'rect',
      x: 0,
      y: 0,
      width: 375,
      height: 563,
      backgroundColor: '#000',
    },
    {
      type: 'image',
      x: 0,
      y: 0,
      url: params.headUrl,
      width: 375,
      height: 375,
    },
    {
      type: 'text',
      x: 16,
      y: 391,
      fontFamily: 'PingFang SC',
      fontSize: 24,
      color: '#FFFEFA',
      text: params.collectionName,
      bold: '700',
      maxWidth: 230,
      ellipse: 1,
    },
    {
      type: 'text',
      x: 16,
      y: 433,
      fontFamily: 'PingFang SC',
      fontSize: 16,
      color: '#5E616D',
      text: '正版三国授权',
      bold: '400',
    },
    {
      type: 'image',
      x: 16,
      y: 487,
      width: 120,
      height: 28,
      url: 'https://zodance.oss-cn-shenzhen.aliyuncs.com/three-kingdoms/dg-collection/poster-logo.png',
    },
    {
      type: 'text',
      x: 16,
      y: 530,
      fontFamily: 'PingFang SC',
      fontSize: 12,
      color: '#5E616D',
      text: '扫码打开三国数藏平台',
      bold: '400',
    },
    {
      type: 'image',
      x: 291,
      y: 479,
      width: 68,
      height: 68,
      url: params.qrcodeUrl,
    },
  ]
}
